name: 'weather_crypto_dbt'
version: '1.0'

profile: 'default'

source-paths:
  - models
  - analysis

target-path: 'target'
clean-targets:
  - 'target'

models:
  staging:
    +materialized: view
  marts:
    +materialized: table